baseURL: 'https://xezpeleta.github.io/'
languageCode: eu-es
title: Xabi Ezpeleta
author: Xabi Ezpeleta
description: Xabiren bloga
keywords: Blog
copyright: 'Copyright © 2021, Xabier Ezpeleta. License [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).'
theme: PaperMod

# Replacing deprecated 'paginate' with new 'pagination.pagerSize'
pagination:
  pagerSize: 5
pluralizeListTitles: false
enableRobotsTXT: true

params:
  ShowCodeCopyButtons: true
  
  # Ikonoak agertzeko, homeInfoParams gehitu behar dut
  # Hutsik uzten badut, margen bat gehitzen dit 320px-koa
  # post-entry.css fitxategian bilatu eta komentatu dut
  homeInfoParams:
    Title:
    Content:

  socialIcons:
  - name: mastodon
    url: "https://mastodon.eus/@xezpeleta"
  - name: github
    url: "https://github.com/xezpeleta"

googleAnalytics: G-ZJRN8P7X6R
analytics:
  google:
    SiteVerificationTag: G-ZJRN8P7X6R

#menu:
#  main:
#    - identifier: categories
#      name: categories
#      url: /categories/
#      weight: 10
#    - identifier: tags
#      name: tags
#      url: /tags/
#      weight: 20

defaultContentLanguage: eu
languages:
  eu:
    languageName: 'Euskara'
    weight: 1
    menu:
      main:
        - name: kategoriak
          url: categories/
          weight: 10
        - name: etiketak
          url: tags/
          weight: 20
  en:
    languageName: 'English'
    weight: 2
    menu:
      main:
        - name: categories
          url: categories/
          weight: 10
        - name: tags
          url: tags/
          weight: 20
